## -*- encoding: utf-8 -*-
## This file (Hartshorne.sagetex.sage) was *autogenerated* from Hartshorne.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('Hartshorne', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
